### ISSUE TITLE
Single GPS location which will include a 25km radius don't work in locationSets

### ISSUE THREAD

**Issue by peternewman** [osmlab/name-suggestion-index#4776]
I've removed the .geojson file and replaced it with a single GPS location which will include a 25km radius of London

_Originally posted by @UKChris-osm in https://github.com/osmlab/name-suggestion-index/pull/4767#discussion_r536883762_

They choke up this:
https://github.com/osmlab/name-suggestion-index/blob/29834b52709919c7b665189444c87044881daf14/lib/file_tree.js#L228-L230

With:
```
/home/travis/build/osmlab/name-suggestion-index/lib/file_tree.js:229

    return str.trim().toLowerCase();

               ^

TypeError: str.trim is not a function

    at _cleanLower (/home/travis/build/osmlab/name-suggestion-index/lib/file_tree.js:229:16)

    at Array.map (<anonymous>)

    at normalItems.filter.sort.map.item (/home/travis/build/osmlab/name-suggestion-index/lib/file_tree.js:178:56)

    at Array.map (<anonymous>)

    at paths.forEach.tkv (/home/travis/build/osmlab/name-suggestion-index/lib/file_tree.js:170:10)

    at Set.forEach (<anonymous>)

    at Object.keys.forEach.t (/home/travis/build/osmlab/name-suggestion-index/lib/file_tree.js:139:11)

    at Array.forEach (<anonymous>)

    at Object.exports.write (/home/travis/build/osmlab/name-suggestion-index/lib/file_tree.js:124:22)

    at saveIndex (/home/travis/build/osmlab/name-suggestion-index/scripts/build_index.js:241:12)
```

Need to either fix validate to catch them or fix file_tree to allow them.

**Comment by bhousel** [comment]
Thanks for raising this - I forgot about those!
I added some code in 392a8fb to better support arraylike location values.

**Comment by peternewman** [comment]
No worries. @UKChris-osm gets the credit for breaking it! :laughing:
