### ISSUE TITLE
Everytime after npm run build it change LR to CRLF

### ISSUE THREAD

**Issue by LaoshuBaby** [osmlab/name-suggestion-index#4983]
I'm running nodejs on Windows, maybe different from developer's

So every time I run this command, it will change all files to CRLF

![微信图片_20210320115131](https://user-images.githubusercontent.com/42690037/111858287-b8860500-8972-11eb-8743-a44a4c5b1a53.jpg)

I guess this is because I'm a windows user.

So will this be like #4850  and #4871 ,is a environment based feature?

>
>每次交PR之前，都会感觉自己被淹没在changed files的海洋里，这太难受了！

![图片](https://user-images.githubusercontent.com/42690037/111858172-c4bd9280-8971-11eb-9d43-183e6bfdb0a1.png)

**Comment by bhousel** [comment]
Oh yeah this is pretty common.. Can you try the suggestion here: https://stackoverflow.com/a/11535140

```bash
git config --global core.autocrlf true
```

I _think_ what that is supposed to do is tell git to not consider a line ending change as significant.  
So your `npm run build` may still change the line endings but git will not consider that a change worth checking in?
Let me know if that works?

**Comment by LaoshuBaby** [comment]
Thanks @bhousel 

But sorry, it don't works……

![图片](https://user-images.githubusercontent.com/42690037/111861229-9d71c000-8987-11eb-92dc-f4782d7ae50b.png)

**Comment by LaoshuBaby** [comment]
Besides, ```npm run test``` will failed because the crlf problem

It is so———— long that I only show the tail of Powershell Terminal

```
  90:2    error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 3892 problems (3887 errors, 5 warnings)
  3887 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name-suggestion-index@5.0.0-pre lint: `eslint scripts/*.js lib/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the name-suggestion-index@5.0.0-pre lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\快乐的老鼠宝宝\AppData\Roaming\npm-cache\_logs\2021-03-20T06_22_48_706Z-debug.log
ERROR: "lint" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! name-suggestion-index@5.0.0-pre test: `run-s lint build jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the name-suggestion-index@5.0.0-pre test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\快乐的老鼠宝宝\AppData\Roaming\npm-cache\_logs\2021-03-20T06_22_48_749Z-debug.log
```

And here is the content in debug log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v14.15.3
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle name-suggestion-index@5.0.0-pre~pretest: name-suggestion-index@5.0.0-pre
6 info lifecycle name-suggestion-index@5.0.0-pre~test: name-suggestion-index@5.0.0-pre
7 verbose lifecycle name-suggestion-index@5.0.0-pre~test: unsafe-perm in lifecycle true
8 verbose lifecycle name-suggestion-index@5.0.0-pre~test: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\快乐的老鼠宝宝\Documents\GitHub\name-suggestion-index\node_modules\.bin;C:\Program Files\Python\Scripts\;C:\Program Files\Python\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;c:\windows\system32;C:\Program Files\PuTTY\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Scala\bin;C:\Program Files (x86)\Scala\jre\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Sqlite;C:\OpenCV\build\x64\vc14\bin;C:\OpenCV\build\x64\vc15\bin;C:\Program Files\Git\cmd;C:\OpenCV\build\x64\vc15\lib;C:\OpenCV\build\x64\vc14\lib;C:\Program Files (x86)\BaseX\bin;C:\Program Files\nodejs\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files\Pandoc\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\快乐的老鼠宝宝\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3\bin;C:\Users\快乐的老鼠宝宝\AppData\Local\GitHubDesktop\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.2\bin;;C:\Program Files\Huawei\DevEco Studio\bin;;C:\Users\快乐的老鼠宝宝\AppData\Roaming\npm;C:\texlive\2020\bin\win32;C:\Users\快乐的老鼠宝宝\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle name-suggestion-index@5.0.0-pre~test: CWD: C:\Users\快乐的老鼠宝宝\Documents\GitHub\name-suggestion-index
10 silly lifecycle name-suggestion-index@5.0.0-pre~test: Args: [ '/d /s /c', 'run-s lint build jest' ]
11 silly lifecycle name-suggestion-index@5.0.0-pre~test: Returned: code: 1  signal: null
12 info lifecycle name-suggestion-index@5.0.0-pre~test: Failed to exec test script
13 verbose stack Error: name-suggestion-index@5.0.0-pre test: `run-s lint build jest`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid name-suggestion-index@5.0.0-pre
15 verbose cwd C:\Users\快乐的老鼠宝宝\Documents\GitHub\name-suggestion-index
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
18 verbose node v14.15.3
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error name-suggestion-index@5.0.0-pre test: `run-s lint build jest`
22 error Exit status 1
23 error Failed at the name-suggestion-index@5.0.0-pre test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by kymckay** [comment]
Hey there! I have some experience with this as a windows user too, is it definitely `npm run build` that's changing the line endings? That seems very unexpected to me and I can't reproduce it.

The usual suspect is git itself changing the line endings upon checkout (controlled by the setting pointed out by @bhousel). The setting itself is pretty badly explained across the web, here's what I've learned from experience:

- `core.autocrlf true`: Upon checkout any LF is converted to CRLF (on windows), upon commit any CRLF is converted to LF (good for project consistency, bad for accuracy on the developer machine as you're running into)
- `core.autocrlf false`: Line endings aren't messed with at all by git (potentially bad for project consistency, good for accuracy on the developer machine)
- `core.autocrlf input`: Line endings aren't messed with on checkout, upon commit any CRLF is converted to LF (good for project consistency, good for accuracy on the developer machine)

So my personal preference is to set to `input` as I'd rather git didn't unexpectedly mess with the files I'm checking out (to avoid these kind of linting issues - I'd rather explicitly set up my editor to handle line endings). After setting this, you may have to mess around with deleting and re-checking out the files to get git to make them all LF again.
