### ISSUE TITLE
run wikidata is failing on JS error

### ISSUE THREAD

**Issue by tas50** [osmlab/name-suggestion-index#5007]
```
$ npm run wikidata

...

Batch 174/174
Updating Wikidata 2:  Removing old NSI identifier for Q3112627: queenslandgovernment-943805
TypeError: Cannot read property 'claim' of undefined
    at processWbEditQueue (/Users/tsmith/dev/oss/name-suggestion-index/scripts/build_wikidata.js:752:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by bhousel** [comment]
Oh I see what's going on - This part of the script needs to be changed to avoid attempting an edit if the person running the script hasn't added their wikidata credentials to `config/secrets.json`.
