### ISSUE TITLE
Issue when tags contains the value 'constructor'

### ISSUE THREAD

**Issue by HLucasTargomo** [osmlab/name-suggestion-index#7875]
Earlier today, a OSM user uploaded a new node with the tag `office=constructor` (changeset: https://www.openstreetmap.org/changeset/133661955 / node: https://www.openstreetmap.org/node/10734659231).

It seems the js library has some issues with such value called 'constructor'. (maybe becase constructor is a special method in js?)
I got this stack trace:
```
TypeError: Found non-callable @@iterator
    at Object._this.matchTags (file:///.../presets/index.js:222:38)
    at gatherKVs (file:///.../core/nsi.js:205:31)
    at _upgradeTags (file:///.../core/nsi.js:451:17)
    at Object.upgradeTags (file:///.../core/nsi.js:731:30)
...
```
when calling `_upgradeTags` with `{"name": "Construtora Coase", "office": "constructor" }` as `tags` parameter.

I solved the issue by updating the OSM node with the good tag `office=construction_company` but I think this error shouldn't have happened in the first place.

**Comment by LaoshuBaby** [comment]
`constructor` is indeed a reserved keyword in JavaScript used to refer to the constructor function of an object. However, it shouldn't cause the error you encountered when used as a value for a key in an object?

![图片](https://user-images.githubusercontent.com/42690037/225098741-c0d9cce7-8d2d-4f3f-ae5e-5dc7add7c525.png)

It appears that we are encountering this issue for the first time, as the tag has never appeared before. ~~I guess that this could be due to a problem with iD/RapiD?~~ We may want to reach out to other maintainers who have expertise in JavaScript to help us address this challenge. 😰

**Comment by UKChris-osm** [comment]
I think this is more of an issue for iD / Rapid than the NSI, as it seems a POI tagged with `constructor` is causing the POI to freeze as iD doesn't know what to do with it?

@tyrasd

**Comment by bhousel** [comment]
Oh yeah, this is https://github.com/openstreetmap/iD/issues/3044
We've known about it for a while - we'd have to switch all tag handling code over to use a modern [ES6 Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).
