### ISSUE TITLE
ubuntu 18.04 + node 10   "TypeError: reader.apply is not a function"

### ISSUE THREAD

**Issue by ImreSamu** [osmlab/name-suggestion-index#93]
I have installed the latest master - on `Ubuntu18.04` +  `node 10`  
and I have received this error message - after running:

```
/osm/name-suggestion-index/getRaw.js:57
reader.apply(handler, { "with_location_handler": false });
       ^

TypeError: reader.apply is not a function
    at Object.<anonymous> (/osm/name-suggestion-index/getRaw.js:57:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
```

My Dockerfile 
```Dockerfile
FROM ubuntu:18.04

RUN apt-get update \
    && apt-get install  -y --no-install-recommends \
       apt-utils \
       build-essential \
       ca-certificates \
       git \
       gcc \
       g++ \
       lsb-release \
       make \
       gnupg2 \
       curl \
       wget \
    && rm -rf /var/lib/apt/lists/

RUN mkdir -p  /osm/name-suggestion-index
WORKDIR /osm/name-suggestion-index

RUN git clone  --quiet --depth 1 https://github.com/osmlab/name-suggestion-index.git /osm/name-suggestion-index
RUN wget http://download.geofabrik.de/europe/monaco-latest.osm.pbf

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
    && apt-get update \
    && apt-get install  -y --no-install-recommends \
       nodejs \
    && npm install \
    && rm -rf /var/lib/apt/lists/

RUN node -v && npm -v
RUN node getRaw ./monaco-latest.osm.pbf
```

**Comment by bhousel** [comment]
I got this error too and I'm pretty sure it was because of changes in node-osmium.  I was able to pin to a newer version and update that code, now I'm able to get it built again (and figured out how to prefilter the planet so these rebuilds actually run much quicker!)

Please hold off for a few days though since I'm currently rearranging the whole project, thanks!
